import { Panel } from "@/components/kit"
import { cn } from "@/utils/cn"
import { Radio, Toggle } from "../wizardComponents"

const APPROVALS = [["never", "Never"], ["high-critical", "For High / Critical"], ["always", "Always"]]
const WINDOWS = [["always", "Always"], ["maintenance-only", "Maintenance Windows Only"]]

export default function Step8Disk({ form, setForm }) {
  const safety = form.safety || {}
  const update = values => setForm(f => ({ ...f, safety: { ...f.safety, ...values } }))
  return <Panel className="p-6"><div className="mb-6"><p className="font-mono text-[10px] uppercase tracking-widest text-primary font-bold">8. SAFETY (APPROVAL & PERMISSIONS)</p><p className="text-xs text-muted-foreground mt-0.5">Control disk cleanup and recovery execution.</p></div><div className="space-y-5"><div className="flex items-center justify-between rounded-md border border-border bg-secondary/10 p-4"><div><p className="font-mono text-xs font-semibold">Automatic Execution</p><p className="font-mono text-[11px] text-muted-foreground">Allow configured disk actions to execute automatically.</p></div><div className="flex items-center gap-2"><Toggle checked={!!safety.autoExec} onChange={v => update({ autoExec: v })} /><span className="font-mono text-xs">{safety.autoExec ? "Enabled" : "Disabled"}</span></div></div><Choice title="Approval Required" options={APPROVALS} value={safety.approvalRequired || "always"} onChange={approvalRequired => update({ approvalRequired })} /><Choice title="Allowed During" options={WINDOWS} value={safety.allowedDuring || "always"} onChange={allowedDuring => update({ allowedDuring })} /><div className="grid grid-cols-1 md:grid-cols-2 gap-3 rounded-md border border-primary/20 bg-primary/5 p-4"><label className="font-mono text-[11px]">Maximum Cleanup Size<input value={safety.maxCleanupSize || ""} onChange={e => update({ maxCleanupSize: e.target.value })} placeholder="5 GB" className="mt-1.5 w-full rounded-md border border-border bg-card px-3 py-2.5 font-mono text-xs" /></label><label className="font-mono text-[11px]">Protected Paths<input value={safety.protectedPaths || ""} onChange={e => update({ protectedPaths: e.target.value })} placeholder="/etc, /var/lib, /home" className="mt-1.5 w-full rounded-md border border-border bg-card px-3 py-2.5 font-mono text-xs" /></label><label className="flex items-center gap-2 font-mono text-xs md:col-span-2"><input type="checkbox" checked={!!safety.dryRun} onChange={e => update({ dryRun: e.target.checked })} /> Dry Run Before Execution</label></div></div></Panel>
}

function Choice({ title, options, value, onChange }) { return <div><p className="font-mono text-xs font-semibold mb-3">{title}</p><div className="grid grid-cols-1 md:grid-cols-3 gap-3">{options.map(([id, label]) => <label key={id} onClick={() => onChange(id)} className={cn("flex items-center justify-between rounded-md border p-3 cursor-pointer", value === id ? "border-primary bg-primary/5" : "border-border hover:border-primary/30")}><span className="font-mono text-xs">{label}</span><Radio checked={value === id} /></label>)}</div></div> }
