import { Info } from "lucide-react"
import { Panel } from "@/components/kit"
import { Checkbox, SelectBox } from "../wizardComponents"

export default function Step9Disk({ form, setForm }) {
  const retry = form.retry || {}
  const update = values => setForm(f => ({ ...f, retry: { ...f.retry, ...values } }))
  return <Panel className="p-6"><div className="mb-6"><p className="font-mono text-[10px] uppercase tracking-widest text-primary font-bold">9. RETRY & COOLDOWN</p><p className="text-xs text-muted-foreground mt-0.5">Configure retry limits and duplicate suppression for disk recovery.</p></div><div className="space-y-5"><div className="flex gap-2 rounded-md border border-primary/20 bg-primary/5 p-3"><Info className="size-4 text-primary shrink-0" /><p className="font-mono text-[11px]">Recovery actions can be retried up to the configured maximum attempt count. Cooldown prevents repeated recovery attempts and duplicate incidents.</p></div><div className="grid grid-cols-1 md:grid-cols-2 gap-5"><label className="font-mono text-[11px]">Maximum Retry Attempts<div className="flex items-center gap-2 mt-1.5"><input type="number" min="0" value={retry.maxAttempts ?? 0} onChange={e => update({ maxAttempts: e.target.value })} className="w-24 rounded-md border border-border bg-card px-3 py-2.5 font-mono text-xs" /><span>attempts</span></div></label><label className="font-mono text-[11px]">Cooldown Period<div className="flex gap-2 mt-1.5"><input type="number" min="0" value={retry.cooldownMinutes ?? 0} onChange={e => update({ cooldownMinutes: e.target.value })} className="w-24 rounded-md border border-border bg-card px-3 py-2.5 font-mono text-xs" /><SelectBox value={retry.cooldownUnit || "Minutes"} options={["Minutes", "Hours"]} onChange={v => update({ cooldownUnit: v })} className="w-28" /></div></label></div><div className="space-y-2"><Check label="Suppress duplicate incidents during cooldown" checked={!!retry.suppressDuplicates} onChange={v => update({ suppressDuplicates: v })} /><Check label="Enable deduplication during cooldown" checked={!!retry.enableDedup} onChange={v => update({ enableDedup: v })} /></div></div></Panel>
}
function Check({ label, checked, onChange }) { return <label className="flex items-center gap-2.5 font-mono text-xs"><Checkbox checked={checked} onClick={() => onChange(!checked)} />{label}</label> }
