import { Globe } from "lucide-react"
import { Panel } from "@/components/kit"
import { cn } from "@/utils/cn"
import { Checkbox, Radio } from "../wizardComponents"

const DAYS = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
const TIMEZONES = ["UTC", "Asia/Colombo", "Asia/Kolkata", "America/New_York"]

export default function Step12Disk({ form, setForm }) {
  const schedule = form.schedule || {}
  const update = values => setForm(f => ({ ...f, schedule: { ...f.schedule, ...values } }))
  const toggleDay = day => update({ days: (schedule.days || []).includes(day) ? schedule.days.filter(item => item !== day) : [...(schedule.days || []), day] })
  return <Panel className="p-6"><div className="mb-6"><p className="font-mono text-[10px] uppercase tracking-widest text-primary font-bold">12. SCHEDULE</p><p className="text-xs text-muted-foreground mt-0.5">Define when the Disk rule is active.</p></div><div className="space-y-6"><div className="grid grid-cols-1 md:grid-cols-2 gap-3">{[["Always Active", "Runs the rule continuously."], ["Custom Schedule", "Set specific days and times."]].map(([id, desc]) => <label key={id} onClick={() => update({ activation: id })} className={cn("flex flex-col gap-1.5 rounded-md border p-4 cursor-pointer", (schedule.activation || "Always Active") === id ? "border-primary bg-primary/5" : "border-border")}><div className="flex justify-between"><span className="font-mono text-xs font-semibold">{id}</span><Radio checked={(schedule.activation || "Always Active") === id} /></div><span className="font-mono text-[10px] text-muted-foreground">{desc}</span></label>)}</div>{schedule.activation === "Custom Schedule" && <div className="space-y-4"><div className="grid grid-cols-2 md:grid-cols-4 gap-2">{DAYS.map(day => <label key={day} className="flex items-center gap-2 rounded-md border p-2.5 font-mono text-[10px]"><Checkbox checked={(schedule.days || []).includes(day)} onClick={() => toggleDay(day)} />{day}</label>)}</div><div className="grid grid-cols-2 gap-3"><label className="font-mono text-xs">Start Time<input type="time" value={schedule.startTime || ""} onChange={e => update({ startTime: e.target.value })} className="mt-1.5 w-full rounded-md border border-border bg-card px-3 py-2.5 font-mono text-xs" /></label><label className="font-mono text-xs">End Time<input type="time" value={schedule.endTime || ""} onChange={e => update({ endTime: e.target.value })} className="mt-1.5 w-full rounded-md border border-border bg-card px-3 py-2.5 font-mono text-xs" /></label></div></div>}<label className="flex items-center gap-2.5 font-mono text-xs"><Checkbox checked={!!schedule.suppressMaintenance} onClick={() => update({ suppressMaintenance: !schedule.suppressMaintenance })} />Suppress alerts during maintenance windows</label><label className="flex items-center gap-2 font-mono text-xs"><Globe className="size-3.5 text-muted-foreground" /><select value={schedule.timezone || "UTC"} onChange={e => update({ timezone: e.target.value })} className="flex-1 rounded-md border border-border bg-card px-3 py-2.5 font-mono text-xs">{TIMEZONES.map(zone => <option key={zone}>{zone}</option>)}</select></label></div></Panel>
}
