import { useEffect } from "react"
import { Panel } from "@/components/kit"
import { SelectBox } from "../wizardComponents"
import { DISK_METRICS, OPERATORS, metricFor, updateDisk } from "./diskHelpers"

export default function Step10Disk({ form, setForm }) {
  const metric = metricFor(form.recoveryMetric || form.metric)
  useEffect(() => { if (!form.recoveryThreshold || !form.recoveryDuration) setForm(f => ({ ...f, recoveryMetric: f.recoveryMetric || f.metric || metric.id, recoveryOperator: f.recoveryOperator || "Less Than (<)", recoveryThreshold: f.recoveryThreshold || (metric.unit === "%" ? "80" : "50"), recoveryDuration: f.recoveryDuration || "5", recoveryDurationUnit: f.recoveryDurationUnit || "Minutes" })) }, [form.recoveryMetric, form.metric, form.recoveryThreshold, form.recoveryDuration, metric.id, metric.unit, setForm])
  return <Panel className="p-6"><div className="mb-6"><p className="font-mono text-[10px] uppercase tracking-widest text-primary font-bold">10. DISK VERIFICATION & RECOVERY</p><p className="text-xs text-muted-foreground mt-0.5">Define how recovery is detected for this disk rule.</p></div><div className="space-y-5"><div className="grid grid-cols-1 md:grid-cols-4 gap-3"><SelectBox value={metric.id} options={DISK_METRICS.map(item => item.id)} onChange={v => updateDisk(setForm, { recoveryMetric: v })} /><SelectBox value={form.recoveryOperator || "Less Than (<)"} options={OPERATORS} onChange={v => updateDisk(setForm, { recoveryOperator: v })} /><input value={form.recoveryThreshold || ""} onChange={e => updateDisk(setForm, { recoveryThreshold: e.target.value })} placeholder="Threshold" className="rounded-md border border-border bg-card px-3 py-2.5 font-mono text-xs" /><span className="flex items-center font-mono text-xs text-muted-foreground">{metric.unit}</span></div><div className="flex gap-3"><input value={form.recoveryDuration || ""} onChange={e => updateDisk(setForm, { recoveryDuration: e.target.value })} placeholder="Duration" className="w-28 rounded-md border border-border bg-card px-3 py-2.5 font-mono text-xs" /><SelectBox value={form.recoveryDurationUnit || "Minutes"} options={["Seconds", "Minutes", "Hours"]} onChange={v => updateDisk(setForm, { recoveryDurationUnit: v })} className="w-32" /></div><p className="rounded-md border border-primary/20 bg-primary/5 p-3 font-mono text-[11px]">The recovery condition must remain satisfied for the configured duration before the incident is marked as recovered.</p></div></Panel>
}
